//window.__DEBUG__ = true;

import { CONSTANTS } from './constantsDefaults.js';

export {
  logError,
  SHRINK_MS,
  DOM_IDS,
  WORKSPACE_EVENTS,
  WORKSPACE_SAVE_URL,
  WORKSPACE_LOAD_URL,
  WORKSPACE_SAVE_DEBOUNCE_MS,
} from './app.js';

export { BLOCK_FORMS } from './blockShapes.js';

export const {
  DEFAULT_BLOCK_COLOR,
  GHOST_BLOCK,
  DEFAULT_BLOCK_HEIGHT,
  CBLOCK_NESTED_X_OFFSET,
  C_BLOCK_EMPTY_INNER_SPACE,
  CONNECTOR_THRESHOLD,
  CONNECTOR_SOCKET_HEIGHT,
  START_BLOCK_NORMAL_STACK_EXTRA_Y,
  MOVE_THRESHOLD,
  CONNECTOR_OFFSETS,
  CONNECTOR_ZONE_STYLE,
  START_BLOCK_MIDDLE_CHAIN_SPLIT_OFFSET,
  STOP_BLOCK_MIDDLE_CHAIN_SPLIT_OFFSET,
  SVG_NS,
  FALLBACK_DARK,
  UUID_ALPHABET,
  WORKSPACE_GRID_CELL_PX,
  WORKSPACE_BLOCK_GRID_SNAP,
  WORKSPACE_CAMERA_INERTIA,
  C_BLOCK_CANONICAL_PATH_EXPECTED_V_COUNT,
  C_BLOCK_INNER_STACK_VERTICAL_LEG_INDICES,
} = CONSTANTS;
